### ISSUE TITLE
resetSwipe() and resetWithAnimationContentPosition() cause other problems

### ISSUE THREAD

**Issue by qcdyx** [samsao/swipeable-list-item#1]
I'm working on an app that has a recyclerview. When the user swipes the recyclerview item from right to left, a datePickerDialog would show up. If the user cancels date selecting, resetSwipe() or resetWithAnimationContentPosition() would be called to reset the swipe.

I met two problems:
1. When resetSwipe() is used,  if the user swipes from right to left a bit and cancels the swiping, the datePickerDialog shows up (But, it should not show up in this user case).
2. When resetWithAnimationContentPosition()  is used, the datePickerDialog keeps showing up when the user cancels date selecting.

Please take a look, thank you!

**Comment by laricampos** [comment]
Working on it!

**Comment by qcdyx** [comment]
Perfect! Thank you!

**Comment by laricampos** [comment]
Fixed! I've also changed the name of the method resetWithAnimationContentPosition() to resetSwipeWithAnimation() to be more intuitive.
